name: Daily Report Automation

on:
  schedule:
    # 매일 한국시간 오전 6시 (UTC 21:00 전날)
    - cron: '0 21 * * *'
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  send-daily-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Send Daily Reports
        run: |
          echo "Sending daily reports for all cells..."

          # Cell 5 리포트 발송
          REPORT_DATE=$(date -d "yesterday" +%Y-%m-%d)
          echo "Report date: $REPORT_DATE"

          curl -X POST "https://nerdx-apec-mvp-production.up.railway.app/api/v1/reports/daily/cell-5ca00d505e2b/send?report_date=$REPORT_DATE" \
            -H "Content-Type: application/json" \
            -f || echo "Failed to send report for Cell 5"

          echo "Daily reports sent successfully!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "::error::Daily report automation failed"
