version: '3.8'

services:
  # Phase 2 Agentic System API
  phase2-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phase2-agentic-api
    ports:
      - "8002:8002"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8002
      - API_ENVIRONMENT=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./tmp:/tmp/nerdx-videos
    networks:
      - nerdx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for queue management
  redis:
    image: redis:7-alpine
    container_name: phase2-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - nerdx-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Redis Commander (optional - for debugging)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: phase2-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - nerdx-network
    profiles:
      - debug

volumes:
  redis-data:
    driver: local

networks:
  nerdx-network:
    driver: bridge
