global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'phase1-api'
    static_configs:
      - targets: ['phase1-api:8001']
    metrics_path: '/metrics'

  - job_name: 'phase2-api'
    static_configs:
      - targets: ['phase2-api:8002']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:7474']
    metrics_path: '/metrics'
