/**
 * Orders Page
 * Auto-generated by Phase A automation
 */

'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function OrdersPage() {
  const router = useRouter();
  const [email, setEmail] = useState('');
  const [orders, setOrders] = useState([]);

  async function handleFetchOrders() {
    // Implementation will fetch from Shopify
    alert('Order history fetching coming soon!');
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">주문 내역</h1>

      {/* Email Input */}
      <div className="bg-white rounded-lg shadow p-6 mb-8">
        <h2 className="text-xl font-semibold mb-4">주문 조회</h2>
        <p className="text-gray-600 mb-4">
          주문 시 사용한 이메일 주소를 입력하여 주문 내역을 확인하세요.
        </p>

        <div className="flex space-x-4">
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="이메일 주소"
            className="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500"
          />
          <button
            onClick={handleFetchOrders}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            조회하기
          </button>
        </div>
      </div>

      {/* Orders List */}
      {orders.length === 0 ? (
        <div className="text-center py-12">
          <p className="text-gray-600 mb-4">주문 내역이 없습니다.</p>
          <button
            onClick={() => router.push('/products/shopify')}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            쇼핑 시작하기
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          {/* Orders will be displayed here */}
        </div>
      )}
    </div>
  );
}
